version: '3.8'

networks:
  private:
    driver: bridge

services:
  app:
    build:
      context: ../escoles
      dockerfile: ../escoles/Dockerfile
    container_name: flask_app
    ports:
      - "5000:5000" # Map host port 5000 to container port 5000
    volumes:
      - ../escoles:/app  # Mount the current directory inside the container (for development)
    environment:
      FLASK_ENV: development # Set Flask environment to development
    ports:
      - "5000:5000"
    networks:
      - private
    stdin_open: true
    tty: true
