version: '3.8'

networks:
  private:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    ports:
      - "5000:5000" # Map host port 5000 to container port 5000
    volumes:
      - .:/app  # Mount the current directory inside the container (for development)
    environment:
      FLASK_ENV: development # Set Flask environment to development
    ports:
      - "5000:5000"
    networks:
      - private
    stdin_open: true
    tty: true

  postgres:
    image: postgres
    restart: always
    env_file:
      - .env  # Specify the .env file to read the environment variables
    ports:
      - "5432:5432"
    networks:
      - private
